CXX = g++
SRCS = main.cpp Character.cpp Vampire.cpp Medusa.cpp Bubba.cpp Game.cpp
HEADERS = Character.h Vampire.h Medusa.h Bubba.h Game.h

Program2: $(SRCS) $(HEADERS)
	$(CXX) $(SRCS) -o prog3

clean:
	rm -f *.o prog3
