CXX = g++
SRCS = Main.cpp Game.cpp Player.cpp Floor.cpp Wombat.cpp Character.cpp
HEADERS = Game.h Player.h Floor.h Wombat.h Character.h

Program1: $(SRCS) $(HEADERS)
	$(CXX) $(SRCS) -o prog4

clean:
	rm -f *.o prog4
