CXX = g++
SRCS = Main.cpp Game.cpp Player.cpp Floor.cpp Wombat.cpp Character.cpp Wall.cpp Entity.cpp Door.cpp Entry.cpp Space.cpp Key.cpp Ladder.cpp Teleport.cpp
HEADERS = Game.h Player.h Floor.h Wombat.h Character.h Wall.h Entity.h Door.h Entry.h Key.h Ladder.h Teleport.h Space.h

Program1: $(SRCS) $(HEADERS)
	$(CXX) $(SRCS) -o prog4

clean:
	rm -f *.o prog4
